name: flutter_axiom
version: 0.1.0+1
description: A Flutter package that sends logs to Axiom for easy debugging and monitoring.
issue_tracker: https://github.com/Avila-Tek/flutter_axiom/issues
homepage: https://github.com/Avila-Tek/flutter_axiom
documentation: https://github.com/Avila-Tek/flutter_axiom

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^0.13.6
  repository: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
